name: "WAS CICD Scan"
description: "Reusable action for running the WAS Scanner in Github Actions"
inputs:
  access_key:
    description: "API Access Key"
    required: true
  secret_key:
    description: "API Access Key"
    required: true
  link_container:
    description: "Use this if you would like to link it up to another container also running on Github Actions on the same runner"
    required: true
  use_petstore_example:
    description: "Would you like to just have this run the documented example?"
    type: choice
    required: false
    default: 'false'
    options:
      - true
      - false
  get-html-report-artifact:
    description: "Would you like to upload a report of the scan in HTML format as an Artifact to Github Actions?"
    type: choice
    required: false
    default: 'true'
    options:
      - true
      - false
runs:
  using: "composite"
  steps:
    - name: "Hello World test"
      run: echo "Hello World"
      shell: bash
    - name: Check if the example needs to be run
      if: ${{ inputs.use_petstore_example == 'true' }}      
      run: |
         docker pull swaggerapi/petstore
         docker run -d -e SWAGGER_URL=http://petstore:8080 -e SWAGGER_BASE_PATH=/v2 --name petstore swaggerapi/petstore
      shell: bash
    - name: Run WAS Scanner
      run: |
        docker pull tenable/was-scanner:latest
        docker run -v $(pwd):/scanner -t \
          -e WAS_MODE=cicd \
          -e ACCESS_KEY=${{ inputs.access_key }} \
          -e SECRET_KEY=${{ inputs.secret_key }} \
          --link ${{ inputs.link_container }} \
          tenable/was-scanner:latest || true
      shell: bash
    - name: Upload HTML Scan Report Artifact
      if: ${{ inputs.get-html-report-artifact == 'true' }} 
      uses: actions/upload-artifact@v4
      with:
        name: scan-vulnerability-output
        path: tenable_was_scan.html
      shell: bash
